### PR TITLE
Verify block_id during block validation

### PR DESCRIPTION
**Pull request by bamrith**

### CODE REVIEW

**Comment by michael-yxchen** [comment]
what would cause this validation to fail?

**Comment by bamrith** [comment]
@michael-yxchen 
> what would cause this validation to fail?

if any of the fields in the block were changed after it was created.

for example, a malicious node could create a block, clone it and change some fields, and propose two different blocks with the same `block_id`. without this check, two honest nodes will vote for both of them when they could be looking at two different payloads.

**Comment by michael-yxchen** [comment]
block_id is not sent over the wire. It's reconstructed by the receiver, so in your example two honest nodes will compute different block_ids with different payloads

**Comment by bamrith** [comment]
oh, i didn't know it was reconstructed by the receiver. this isn't required then.

**Pull request closed without merging**
