### PR TITLE
Add randao validation to blocksync

### PR DESCRIPTION
**Pull request by eclark0426**

### CODE REVIEW

**Comment by omegablitz** [comment]
What was the motivation for this? Asking because relevant to #941

**Comment by ariqchowdhury** [comment]
> What was the motivation for this? Asking because relevant to #941

https://github.com/monad-crypto/monad-internal/issues/304
This issue was what flagged that this was missing, the block policy checks are split and they shouldn't be. Randao is not necessarily special and needing to be checked for blocksync but we should be consistent with block-policy checks and do all of them. Txns need to be validated because we need to get the nonces and gas-params

**Comment by omegablitz** [comment]
Ok, rolled these changes into https://github.com/monad-crypto/monad-bft/pull/941

**Comment by eclark0426** [comment]
Closing this PR in favor of #941 which now incorporates these changes

**Pull request closed without merging**
